game_data = [
    {
        "name": "Chris Evans",
        "follower_count": 39,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Scarlett Johansson",
        "follower_count": 38,
        "description": "Actress",
        "country": "USA",
    },
    {
        "name": "Robert Downey Jr.",
        "follower_count": 37,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Mark Ruffalo",
        "follower_count": 36,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Tom Hiddleston",
        "follower_count": 35,
        "description": "Actor",
        "country": "UK",
    },
    {
        "name": "Brie Larson",
        "follower_count": 34,
        "description": "Actress",
        "country": "USA",
    },
    {
        "name": "Jeremy Renner",
        "follower_count": 33,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Paul Rudd",
        "follower_count": 32,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Chadwick Boseman",
        "follower_count": 31,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Benedict Cumberbatch",
        "follower_count": 30,
        "description": "Actor",
        "country": "UK",
    },
    {
        "name": "Elizabeth Olsen",
        "follower_count": 29,
        "description": "Actress",
        "country": "USA",
    },
    {
        "name": "Anthony Mackie",
        "follower_count": 28,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Sebastian Stan",
        "follower_count": 27,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Tom Hardy",
        "follower_count": 26,
        "description": "Actor",
        "country": "UK",
    },
    {
        "name": "Ryan Reynolds",
        "follower_count": 25,
        "description": "Actor",
        "country": "Canada",
    },
    {
        "name": "Hugh Jackman",
        "follower_count": 24,
        "description": "Actor",
        "country": "Australia",
    },
    {
        "name": "Jake Gyllenhaal",
        "follower_count": 23,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Zendaya",
        "follower_count": 22,
        "description": "Actress and singer",
        "country": "USA",
    },
    {
        "name": "Zoe Saldana",
        "follower_count": 21,
        "description": "Actress",
        "country": "USA",
    },
    {
        "name": "Chris Pratt",
        "follower_count": 20,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Vin Diesel",
        "follower_count": 19,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Gal Gadot",
        "follower_count": 18,
        "description": "Actress",
        "country": "Israel",
    },
    {
        "name": "Jason Momoa",
        "follower_count": 17,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Dwayne Johnson",
        "follower_count": 16,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Henry Cavill",
        "follower_count": 15,
        "description": "Actor",
        "country": "UK",
    },
    {
        "name": "Margot Robbie",
        "follower_count": 14,
        "description": "Actress",
        "country": "Australia",
    },
    {
        "name": "Chris Hemsworth",
        "follower_count": 13,
        "description": "Actor",
        "country": "Australia",
    },
    {
        "name": "Emma Watson",
        "follower_count": 12,
        "description": "Actress",
        "country": "UK",
    },
    {
        "name": "Daniel Radcliffe",
        "follower_count": 11,
        "description": "Actor",
        "country": "UK",
    },
    {
        "name": "Emma Stone",
        "follower_count": 10,
        "description": "Actress",
        "country": "USA",
    }
    ,
    {
        "name": "Ryan Gosling",
        "follower_count": 9,
        "description": "Actor",
        "country": "Canada",
    },
    {
        "name": "Natalie Portman",
        "follower_count": 8,
        "description": "Actress",
        "country": "USA",
    },
    {
        "name": "Leonardo DiCaprio",
        "follower_count": 7,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Brad Pitt",
        "follower_count": 6,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Angelina Jolie",
        "follower_count": 5,
        "description": "Actress",
        "country": "USA",
    },
    {
        "name": "Johnny Depp",
        "follower_count": 4,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Keanu Reeves",
        "follower_count": 3,
        "description": "Actor",
        "country": "Canada",
    },
    {
        "name": "Will Smith",
        "follower_count": 2,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Jennifer Lawrence",
        "follower_count": 1,
        "description": "Actress",
        "country": "USA",
    },
    {
        "name": "Meryl Streep",
        "follower_count": 0,
        "description": "Actress",
        "country": "USA",
    }
]
